class_name NotifUtils extends Object

const NOTIFICATION_LUT : Dictionary = {
	Object.NOTIFICATION_POSTINITIALIZE : "NOTIFICATION_POSTINITIALIZE",
	Object.NOTIFICATION_PREDELETE : "NOTIFICATION_PREDELETE",
	Object.NOTIFICATION_EXTENSION_RELOADED : "NOTIFICATION_EXTENSION_RELOADED",
	Node.NOTIFICATION_ENTER_TREE : "NOTIFICATION_ENTER_TREE",
	Node.NOTIFICATION_EXIT_TREE : "NOTIFICATION_EXIT_TREE",
	Node.NOTIFICATION_MOVED_IN_PARENT : "NOTIFICATION_MOVED_IN_PARENT",
	Node.NOTIFICATION_READY : "NOTIFICATION_READY",
	Node.NOTIFICATION_PAUSED : "NOTIFICATION_PAUSED",
	Node.NOTIFICATION_UNPAUSED : "NOTIFICATION_UNPAUSED",
	Node.NOTIFICATION_PHYSICS_PROCESS : "NOTIFICATION_PHYSICS_PROCESS",
	Node.NOTIFICATION_PROCESS : "NOTIFICATION_PROCESS",
	Node.NOTIFICATION_PARENTED : "NOTIFICATION_PARENTED",
	Node.NOTIFICATION_UNPARENTED : "NOTIFICATION_UNPARENTED",
	Node.NOTIFICATION_SCENE_INSTANTIATED : "NOTIFICATION_SCENE_INSTANTIATED",
	Node.NOTIFICATION_DRAG_BEGIN : "NOTIFICATION_DRAG_BEGIN",
	Node.NOTIFICATION_DRAG_END : "NOTIFICATION_DRAG_END",
	Node.NOTIFICATION_PATH_RENAMED : "NOTIFICATION_PATH_RENAMED",
	Node.NOTIFICATION_CHILD_ORDER_CHANGED : "NOTIFICATION_CHILD_ORDER_CHANGED",
	Node.NOTIFICATION_INTERNAL_PROCESS : "NOTIFICATION_INTERNAL_PROCESS",
	Node.NOTIFICATION_INTERNAL_PHYSICS_PROCESS : "NOTIFICATION_INTERNAL_PHYSICS_PROCESS",
	Node.NOTIFICATION_POST_ENTER_TREE : "NOTIFICATION_POST_ENTER_TREE",
	Node.NOTIFICATION_DISABLED : "NOTIFICATION_DISABLED",
	Node.NOTIFICATION_ENABLED : "NOTIFICATION_ENABLED",
	Node.NOTIFICATION_RESET_PHYSICS_INTERPOLATION : "NOTIFICATION_RESET_PHYSICS_INTERPOLATION",
	Node.NOTIFICATION_EDITOR_PRE_SAVE : "NOTIFICATION_EDITOR_PRE_SAVE",
	Node.NOTIFICATION_EDITOR_POST_SAVE : "NOTIFICATION_EDITOR_POST_SAVE",
	Node.NOTIFICATION_WM_MOUSE_ENTER : "NOTIFICATION_WM_MOUSE_ENTER",
	Node.NOTIFICATION_WM_MOUSE_EXIT : "NOTIFICATION_WM_MOUSE_EXIT",
	Node.NOTIFICATION_WM_WINDOW_FOCUS_IN : "NOTIFICATION_WM_WINDOW_FOCUS_IN",
	Node.NOTIFICATION_WM_WINDOW_FOCUS_OUT : "NOTIFICATION_WM_WINDOW_FOCUS_OUT",
	Node.NOTIFICATION_WM_CLOSE_REQUEST : "NOTIFICATION_WM_CLOSE_REQUEST",
	Node.NOTIFICATION_WM_GO_BACK_REQUEST : "NOTIFICATION_WM_GO_BACK_REQUEST",
	Node.NOTIFICATION_WM_SIZE_CHANGED : "NOTIFICATION_WM_SIZE_CHANGED",
	Node.NOTIFICATION_WM_DPI_CHANGE : "NOTIFICATION_WM_DPI_CHANGE",
	Node.NOTIFICATION_VP_MOUSE_ENTER : "NOTIFICATION_VP_MOUSE_ENTER",
	Node.NOTIFICATION_VP_MOUSE_EXIT : "NOTIFICATION_VP_MOUSE_EXIT",
	Node.NOTIFICATION_OS_MEMORY_WARNING : "NOTIFICATION_OS_MEMORY_WARNING",
	Node.NOTIFICATION_TRANSLATION_CHANGED : "NOTIFICATION_TRANSLATION_CHANGED",
	CanvasItem.NOTIFICATION_TRANSFORM_CHANGED : "NOTIFICATION_TRANSFORM_CHANGED",
	CanvasItem.NOTIFICATION_LOCAL_TRANSFORM_CHANGED : "NOTIFICATION_LOCAL_TRANSFORM_CHANGED",
	CanvasItem.NOTIFICATION_DRAW : "NOTIFICATION_DRAW",
	CanvasItem.NOTIFICATION_VISIBILITY_CHANGED : "NOTIFICATION_VISIBILITY_CHANGED",
	CanvasItem.NOTIFICATION_ENTER_CANVAS : "NOTIFICATION_ENTER_CANVAS",
	CanvasItem.NOTIFICATION_EXIT_CANVAS : "NOTIFICATION_EXIT_CANVAS",
	CanvasItem.NOTIFICATION_WORLD_2D_CHANGED : "NOTIFICATION_WORLD_2D_CHANGED",
}

static func int_to_str(notif_id: int) -> String:
	return NOTIFICATION_LUT.get(notif_id, "%s" % notif_id)

const LIFE_CYLE_NOTIFICATIONS := [
	Node.NOTIFICATION_ENTER_TREE,
	Node.NOTIFICATION_EXIT_TREE,
	Object.NOTIFICATION_POSTINITIALIZE,
	Object.NOTIFICATION_PREDELETE
]
static func log_node_life_cycle(node: Node, notif_id: int) -> void:
	if notif_id in LIFE_CYLE_NOTIFICATIONS:
		print("%s - %s" % [node.name, int_to_str(notif_id)])
